[%
    T = {
        configure_1                                = "Report Services: Configure",
        configure_2                                = "Home",
        configure_3                                = "Plugins",
        configure_4                                = "&rsaquo; Report Services &rsaquo; Configuration",
        configure_5                                = "Allowed Kohan SQL report IDs for the /reportservices/report endpoint by client ID:",
        configure_6                                = "Save",
        configure_7                                = "Configure in YAML format as follows:",
        configure_8                                = "[API client ID/borrowernumber]:",
        configure_9                                = "- [report ID allowed to run]",
        configure_10                               = "Example:",
        configure_11                               = "Update/Upgrade status",
        configure_12                               = "Plugin settings were last updated by borrowernumber",
        configure_13                               = "Plugin was last upgraded on this system on",
        configure_14                               = "Plugin has never been upgraded.",
    }
%]
