[%
    T = {
        configure_1                                = "Raportteri: Konfiguraatio",
        configure_2                                = "Home",
        configure_3                                = "Liitännäiset",
        configure_4                                = "&rsaquo; Raportteri &rsaquo; konfiguraatio",
        configure_5                                = "Raporttirajapinnan /reportservices/report ajettavaksi sallittavat Kohan sql-raporttien id:t asiakas-id:n mukaan:",
        configure_6                                = "Tallenna",
        configure_7                                = "Konfiguroi yaml-muodossa seuraavasti:",
        configure_8                                = "[rajapintaa käyttävän api-asiakkaan asiakas-id/borrowernumber]:",
        configure_9                                = "- [ajettavaksi sallittava raportti-id]",
        configure_10                               = "Esimerkki:",
        configure_11                               = "Päivitä tila",
        configure_12                               = "Liitännäisen asetukset päivitettiin viimeksi asiakkaan toimesta",
        configure_13                               = "Liitännäinen päivitettiin viimeksi tällä järjestelmällä",
        configure_14                               = "Liitännäistä ei ole koskaan päivitetty.",
    }
%]
