[%
    T = {
        configure_1                                = "Rapporteringstjänst: Konfiguration",
        configure_2                                = "Hem",
        configure_3                                = "Tillägg",
        configure_4                                = "&rsaquo; Rapporteringstjänst &rsaquo; konfiguration",
        configure_5                                = "Tillåtna Koha SQL-rapport-ID:n för /reportservices/report baserat på klient-ID:",
        configure_6                                = "Spara",
        configure_7                                = "Konfigurera i YAML-format enligt följande:",
        configure_8                                = "[API-klientens klient-ID/låntagar-ID]:",
        configure_9                                = "- [tillåtet rapport-ID]",
        configure_10                               = "Till exempel:",
        configure_11                               = "Uppdatera/uppgradera status",
        configure_12                               = "Plugin-inställningar uppdaterades senast av låntagarnummer",
        configure_13                               = "Plugin har aldrig uppgraderats.",
        configure_14                               = "Plugin uppgraderades senast på detta system den",
    }
%]
